name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -U pip
          pip install -e .
          pip install pytest flake8
      - name: Lint
        run: flake8
      - name: Tests
        run: pytest -q
      - name: Sample conversion (pandas)
        run: talend2py convert --input examples/jobs/sample_talend_job/sample_job.item --out build/sample --engine pandas
